[project]
name = "finaltask"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-flink==2.3.0",
    "kafka-python>=3.0.11",
    "pyarrow>=16.1.0",
]

[project.scripts]
finaltask = "finaltask:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
