[project]
name = "finaltask"
version = "0.1.0"
description = "End-to-end e-commerce streaming and batch data platform"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-flink==2.2.1",
    "apache-flink-libraries==2.2.1",
    "hdfs>=2.7.3",
    "kafka-python>=3.0.11",
    "pyarrow>=16.1.0",
    "pyspark==3.5.8",
]

[project.scripts]
finaltask = "finaltask:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
